"""
StreamingPlatformAdapter — abstract base class and TrackToken dataclass.

All platform adapters implement this interface. Business logic never touches
platform APIs directly; it goes through adapters only.
"""

from __future__ import annotations

import hashlib
from abc import ABC, abstractmethod
from dataclasses import dataclass, field


@dataclass
class TrackToken:
    """
    Canonical representation of a track as it enters the system.

    Fields that are unavailable from a given source are left as None.
    track_pk is generated by the normaliser after ingestion, not here.
    """
    # Platform identifiers
    source_platform: str          # 'ytm', 'spotify', 'csv', 'manual'
    platform_track_id: str | None = None   # YTM videoId, Spotify track_id, etc.
    platform_uri: str | None = None        # spotify:track:xxx or YTM URL

    # Core metadata (raw, pre-normalisation)
    raw_title: str = ""
    raw_artist: str = ""
    raw_album: str | None = None
    duration_ms: int | None = None
    release_date: str | None = None
    explicit: bool = False

    # Identity fields (populated by enrichment or source)
    isrc: str | None = None

    # Post-normalisation (filled by normalise.py)
    canonical_title: str = ""
    canonical_artist: str = ""
    normalized_title: str = ""
    normalized_artist: str = ""
    track_pk: str = ""

    # Playlist context (populated during YTM fetch)
    added_at: str | None = None   # ISO8601 when track was added to library

    # Carry-through for enrichment pipeline
    extra: dict = field(default_factory=dict)


class StreamingPlatformAdapter(ABC):
    """
    Abstract base for all platform adapters.

    fetch_library_snapshot  — full library pull (all saved tracks)
    fetch_playlist_tracks   — tracks from a specific playlist
    write_playlist          — overwrite or patch a playlist
    resolve_track_ids       — map canonical track_pks back to platform IDs
    """

    @abstractmethod
    def fetch_library_snapshot(self) -> list[TrackToken]:
        """Return all tracks in the user's saved library."""
        ...

    @abstractmethod
    def fetch_playlist_tracks(self, playlist_id: str) -> list[TrackToken]:
        """Return all tracks in the given playlist."""
        ...

    @abstractmethod
    def write_playlist(
        self,
        playlist_id: str,
        track_ids: list[str],
        playlist_name: str | None = None,
    ) -> str:
        """
        Replace or update a playlist with the given platform track IDs.
        Returns the playlist_id (creates playlist if playlist_id is None).
        """
        ...

    @abstractmethod
    def resolve_track_ids(
        self,
        track_pks: list[str],
    ) -> dict[str, str | None]:
        """
        Map internal track_pks to platform-native IDs.
        Returns {track_pk: platform_id_or_None}.
        """
        ...
